### ISSUE TITLE
Global leak error in mocha

### ISSUE THREAD

**Issue by AmicoJoules** [goulash1971/uri-parser#1]
We are using a library that is dependant on this library and some of our unit tests are failing with error message

`Error: global leak detected: Parser`

`node` version is 8
`mocha` version is 5

**Comment by acrodrig** [comment]
Hi, this is a priority for us. Can you help We cannot run tests on Plivo because of this.

**Comment by goulash1971** [comment]
Updated and published as 1.0.1
